site_name: pyAQSC documentation
theme:
  name: readthedocs
  highlightjs: true
nav:
  - Home: 'index.md'
  - Background:
    - Introduction: 'background-intro.md'
    - Governing equations: 'background-governing.md'
    - Free parameters: 'background-free-params.md'
    - Solves for: 'background-solves-for.md'
  - Tutorial:
    - 'Quick start': 'quick-start.md'
    - 'New QS equilibria': 'init-and-iterate-eq.md'
    - 'New QS magnetic field': 'init-and-iterate-mag.md'
    - 'Data structures': 'data-structure.md'
    - 'Plotting': 'plotting.md'
    - 'GPU and auto-differentiation': 'JAX.md'
  - 'API guide': 
    - 'Equilibrium': 'api-equilibrium.md'
    - 'ChiPhiFunc': 'api-chiphifunc.md'
    - 'ChiPhiEpsFunc': 'api-chiphiepsfunc.md'
    - 'Iteration': 'api-iteration.md'
    - 'DESC output': 'api-desc.md'
    - 'Math utilities and solvers': 'api-utils.md'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - mdx_math:
      # How do I set this? 
      enable_dollar_delimiter: True

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

