;;; -*- Mode: LISP; package:maxima; syntax:common-lisp; -*- 
(in-package :maxima)
(DSKSETQ $LHS_NM_CONST_COS
         '((MTIMES SIMP) (($IS_SMALLER SIMP) 0. $M) (($IS_INTEGER SIMP) $M)
           ((%SUM SIMP)
            ((MTIMES SIMP)
             (($IS_SMALLER SIMP) 0. ((MPLUS SIMP) ((MTIMES SIMP) -1. $I3) $N))
             (($IS_SMALLER SIMP) $M
              ((MPLUS SIMP) ((MTIMES SIMP) 2. $I3) ((MTIMES SIMP) -1. $N)))
             ((|$B_alpha_cos_coef| SIMP ARRAY)
              ((MPLUS SIMP) ((MTIMES SIMP) 2. $I3) ((MTIMES SIMP) -1. $N)) $M)
             (($IS_BOTH_EVEN_ODD SIMP)
              ((MPLUS SIMP) ((MTIMES SIMP) 2. $I3) ((MTIMES SIMP) -1. $N)) $M)
             (($IS_INTEGER SIMP) ((MPLUS SIMP) ((MTIMES SIMP) -1. $I3) $N))
             (($IS_SMALLER SIMP) ((MPLUS SIMP) ((MTIMES SIMP) -1. $I3) $N) $I3)
             ((%SUM SIMP)
              ((MTIMES SIMP) ((|$B_alpha_coef| SIMP ARRAY) $I228)
               ((|$B_alpha_coef| SIMP ARRAY)
                ((MPLUS SIMP) ((MTIMES SIMP) -1. $I228) ((MTIMES SIMP) -1. $I3)
                 $N)))
              $I228 0. ((MPLUS SIMP) ((MTIMES SIMP) -1. $I3) $N)))
            $I3 (($CEILING SIMP) ((MTIMES SIMP) 0.5 $N)) (($FLOOR SIMP) $N)))) 
(ADD2LNC '$LHS_NM_CONST_COS $VALUES) 